name: Journey:Dev
#Google Analytics
google_analytics: UA-167474518-1
permalink: /:title.html
category: undefined
url: https://journey-dev.com
description: A journey of coding, motivational tips and productivity hacks. New post every Sunday and Wednesday.
